site_name: "Mutayyab Majeed"
site_description: "Exploring AI, Machine Learning, and Real-World Applications"
site_author: "Mutayyab Majeed"
site_url: "https://mutayyabmajeed.github.io"
# theme: "readthedocs"
